name: Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Image Name
        run: |
          IMAGE_NAME="davidzz/ca-wildfire:${GITHUB_SHA:0:7}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
      - name: Build Image
        run: |
          docker build --rm --force-rm -t "${IMAGE_NAME}" .
          echo -n "Built image size: "
          docker images "${IMAGE_NAME}" --format "{{.Size}}"
      - name: Test and coverage
        run:  >
          docker run --rm -e MAPBOX_TOKEN="${{secrets.MAPBOX_TOKEN}}" "${IMAGE_NAME}"
          python -m pytest --cov=src --headless -vv tests/
      - name: Login to Dockerhub
        run: >
          echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login
          -u '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      - name: Push to Dockerhub
        run: docker push "${IMAGE_NAME}"
      - name: Substitute image name for fly deploy template
        uses: danielr1996/envsubst-action@1.0.0
        env:
            VERSION: 1.2.3
            INSTANCE: staging
        with:
          input: fly.toml.template
          output: fly.toml
      - name: Deploy to Fly
        uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
